# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carid', models.AutoField(primary_key=True, serialize=False)),
                ('CarModel', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=8)),
            ],
        ),
    ]
