# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veichal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('countryname', models.CharField(max_length=200)),
                ('carid', models.ForeignKey(db_column='carid', on_delete=django.db.models.deletion.DO_NOTHING, to='Veichal.Car')),
            ],
        ),
    ]
